services:
  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/nodegoat:${IMAGE_TAG}
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    depends_on:
      mongo:
        condition: service_healthy
    command: sh -c "node artifacts/db-reset.js && npm start"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nodegoat-compose-network

  mongo:
    image: mongo:4.4
    user: mongodb
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nodegoat-compose-network
    
volumes:
  mongo_data:

networks:
  nodegoat-compose-network:
    driver: bridge
