name: Deploy to EC2

on:
  workflow_dispatch:
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name: SSH into EC2
              uses: appleboy/ssh-action@v1.2.2
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    if command -v docker >/dev/null 2>&1; then
                        echo "Docker is already installed"
                    else 
                        echo "Docker is not installed"
                        sudo apt update
                        sudo apt install -y docker.io
                        usermod -aG docker $USER
                        newgrp docker

                    fi


                    if  docker compose version >/dev/null 2>&1; then
                        echo "Docker compose is already installed"
                    else
                        echo "Docker Compose is not installed"
                         sudo apt install docker-compose-v2 -y
                    fi