name: Dockerfile Lint

on:
  workflow_dispatch:

jobs:
    dockerfile-lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name: Run Hadolint
              uses: hadolint/hadolint-action@v3.3.0
              with:
                dockerfile: Dockerfile