name: Docker Build

on:
  workflow_dispatch:

jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name: Build Docker image
              run: docker build -t nodegoat:ci .

            - name: Save Docker image
              run: docker save nodegoat:ci -o nodegoat.tar

            - name: Upload Docker image
              uses: actions/upload-artifact@v4
              with:
                name: nodegoat-image
                path: nodegoat.tar