name: Main Pipeline

on:
  workflow_dispatch:

jobs:
    lint:
        uses: ./.github/workflows/lint.yml

    test:
        needs: lint
        uses: ./.github/workflows/test.yml

    sast:
        needs: [lint, test]
        uses: ./.github/workflows/sast.yml

    secret-scan:
        needs: [lint, test]
        uses: ./.github/workflows/secret-scan.yml

    dependency-scan:
        needs: [lint, test]
        uses: ./.github/workflows/dependency-scan.yml

    dockerfile-lint:
        needs: [lint, test]
        uses: ./.github/workflows/dockerfile-lint.yml

    docker-build:
        needs: [sast, secret-scan, dependency-scan, dockerfile-lint]
        uses: ./.github/workflows/docker-build.yml

