name: SAST

on:
  workflow_call:

jobs:
    sast:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name:  Install Semgrep
              run: | 
                python3 -m pip install semgrep

            - name:  Run Semgrep SAST
              run: |
                semgrep scan --config=auto --json --output=semgrep-report.json

            - name: Upload Semgrep report
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                name: semgrep-report
                path: semgrep-report.json
            