name: Secret Scan

on:
  workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v2