name: ZAP DAST

on:
  workflow_call:
    inputs:
      target:
        description: "Application URL to scan"
        type: string
        required: true

jobs:
    zap-dast:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v7

            - name: Run OWASP ZAP
              uses: zaproxy/action-baseline@v0.15.0
              with:
                target: ${{ inputs.target }}
                allow_issue_writing: false
